USE ANAND;

CREATE TABLE EMPLOYEE(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    POSITION VARCHAR(10),
    SALARY INT
);

DROP TABLE EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(1,"ANAND",'ADMIN',275000);
INSERT INTO EMPLOYEE VALUES(2,"SHARATH",'MANAGER',200000);
INSERT INTO EMPLOYEE VALUES(3,"AKILESH",'SALES',100000);
INSERT INTO EMPLOYEE VALUES(4,"BHARATH",'SALES',100000);
INSERT INTO EMPLOYEE VALUES(5,"SAKTHIVEL",'HR',250000);
INSERT INTO EMPLOYEE VALUES(6,"VASANTH",'HR',250000);
INSERT INTO EMPLOYEE VALUES(7,"HEMALATHA",'CEO',300000);
INSERT INTO EMPLOYEE VALUES(8,"VARSHA",'MANAGER',200000);
INSERT INTO EMPLOYEE VALUES(9,"SRI HARINI",'MANAGER',200000);
INSERT INTO EMPLOYEE VALUES(10,"KARTHIKA",'HR',250000);
INSERT INTO EMPLOYEE VALUES(11,"POOJA",'HR',250000);
INSERT INTO EMPLOYEE VALUES(12,"VIMAL MARIA RAJ",'ENGINEER',100000);
INSERT INTO EMPLOYEE VALUES(13,"ROBO",'ENGINEER',100000);
INSERT INTO EMPLOYEE VALUES(14,"%ana%",'ENGINEER',100000);

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE POSITION="HR";

SELECT * FROM EMPLOYEE
WHERE SALARY>200000;

SELECT * FROM EMPLOYEE
WHERE SALARY<>100000;   -- "<>" this is for NOT EQUAL

SELECT EMP_NAME FROM EMPLOYEE
WHERE SALARY<>100000 AND POSITION="HR";
/*
SELECT * FROM EMPLOYEE
WHERE POSITION="SALES" OR POSITION="HR";
*/
SELECT * FROM EMPLOYEE
WHERE POSITION IN("hr",'sales');

SELECT * FROM EMPLOYEE
WHERE POSITION NOT IN ("hr",'sales',"ADMIN");

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 175000 AND 250000;

SELECT * FROM EMPLOYEE
LIMIT 4;

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 175000 AND 250000
LIMIT 5;

-- LIKE
-- WILDCRADS %(ZERO OR MORE CHARACTERS) _(ONE CHARACTER)

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "A%";  -- name starting with letter "A"

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "%I%";   -- name with letter "i" in except starting and ending

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "__I%";    -- name with third letter "i"

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "%/%";

DELETE FROM employee
WHERE EMP_ID=14;      -- DELETING THE EMPLOYRR ID AS 14

UPDATE EMPLOYEE
SET POSITION="SALES"
WHERE EMP_ID IN(3,4);

UPDATE EMPLOYEE
SET POSITION="ANALYST"
WHERE POSITION="SALES";

UPDATE EMPLOYEE
SET EMP_ID=0
WHERE EMP_ID=1;

UPDATE EMPLOYEE
SET EMP_ID=1
WHERE EMP_ID=0;

SELECT * FROM EMPLOYEE;

SELECT POSITION FROM EMPLOYEE
GROUP BY POSITION;

SELECT DISTINCT POSITION FROM EMPLOYEE;

/* 
		ORDER BY
*/

SELECT * FROM employee
ORDER BY EMP_NAME;   -- NAME IN ALPHABET ORDER 

SELECT * FROM employee
ORDER BY SALARY;     -- SALARY IN INCERASING ORDER

SELECT * FROM employee
ORDER BY SALARY DESC;  -- SALARY IN DECREASING ORDER

SELECT * FROM employee
ORDER BY SALARY,EMP_NAME;  -- SALARY AND NAME IN ASCENDING ORDER

SELECT * FROM employee
WHERE POSITION="HR"
ORDER BY SALARY,EMP_NAME;    -- SALARY AND NAME IN ASCENDING ORDER ONLY ON "HR"

SELECT * FROM employee
ORDER BY ( CASE POSITION    -- CUSTOM ORDER
WHEN 'CEO' THEN 1
WHEN 'ADMIN' THEN 2
WHEN 'MANAGER' THEN 3
WHEN 'HR' THEN 4
ELSE 100          -- ELSE is optional
END
),EMP_NAME;

