USE ANAND;

DROP TABLE EMPLOYEE;
DROP TABLE BRANCH;

CREATE TABLE BRANCH(
BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
BRANCH_NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(50)
);

CREATE TABLE EMPLOYEE(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,			
    EMP_NAME VARCHAR(20) NOT NULL,    				
    POSITION VARCHAR(10) DEFAULT 'UNASSIGNED',  	  
    SALARY INT,								
    BRANCH_ID INT,
    CONSTRAINT FK_BRANCH_ID FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
    ON DELETE SET NULL		-- SET NULL OR CASCADE
);

-- SET NULL if row deleted in branch table and in the employee table foreign ket is setted null
-- CASCADE it will delete the entire row in employee table if we delete foreign key in branch table

INSERT INTO EMPLOYEE VALUES(1,"ANAND",'ADMIN',275000,3);
INSERT INTO EMPLOYEE VALUES(2,"SHARATH",'MANAGER',200000,3);
INSERT INTO EMPLOYEE VALUES(3,"AKILESH",'SALES',100000,2);
INSERT INTO EMPLOYEE VALUES(4,"BHARATH",'SALES',100000,2);
INSERT INTO EMPLOYEE VALUES(5,"SAKTHIVEL",'HR',250000,1);
INSERT INTO EMPLOYEE VALUES(6,"VASANTH",'HR',250000,3);
INSERT INTO EMPLOYEE VALUES(7,"HEMALATHA",'CEO',300000,3);
INSERT INTO EMPLOYEE VALUES(8,"VARSHA",'MANAGER',200000,1);
INSERT INTO EMPLOYEE VALUES(9,"SRI HARINI",'MANAGER',200000,2);
INSERT INTO EMPLOYEE VALUES(10,"KARTHIKA",'HR',250000,1);
INSERT INTO EMPLOYEE VALUES(11,"POOJA",'HR',250000,3);
INSERT INTO EMPLOYEE VALUES(12,"VIMAL MARIA RAJ",'ENGINEER',100000,1);
INSERT INTO EMPLOYEE VALUES(13,"ROBO",'ENGINEER',100000,NULL);
INSERT INTO EMPLOYEE VALUES(14,"%ana%",'ENGINEER',100000,NULL);


INSERT INTO BRANCH VALUES(1,'CHENNAI','DUBAI BUS STAND');
INSERT INTO BRANCH VALUES(2,'MUMBAI','MUMBAI BUS STAND');
INSERT INTO BRANCH VALUES(3,'BANGALORE','BANGALORE BUS STAND');

ALTER TABLE BRANCH 
MODIFY BRANCH_NAME VARCHAR(30);

UPDATE BRANCH
SET BRANCH_NAME='CHENNAI BUS STAND'
WHERE BRANCH_ID=1;

SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;

DELETE FROM BRANCH 
WHERE BRANCH_ID=3;