USE ANAND;

SELECT * FROM EMPLOYEE;
SELECT * FROM BRANCH;

-- I NEED CHENNAI BRANCH EMPLOYEE
-- FIRST FIND CHENNAI BRANCH ID IN BRANCH TABLE AND SEARCH IN EMPLOYEE TABLE BRANCH ID

SELECT * FROM employee
WHERE BRANCH_ID=(SELECT BRANCH_ID FROM BRANCH WHERE BRANCH_NAME='CHENNAI');

-- MINIMUM SALARY EMPLOYEE
SELECT * FROM EMPLOYEE
WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEE);

-- EXISTS 
-- IT USUALLY USED WITH SUB QUERIES

SELECT BRANCH_ID,BRANCH_NAME
FROM BRANCH
WHERE EXISTS (						-- EXISTS - THE CONDTION IS SATISFIED IT WILL WHATEVER THE USER TELLS AND NO ONE IS SATISFIED IT WILL NOT PRINT
SELECT * FROM EMPLOYEE WHERE POSITION='ADMIN'
);
